version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - some_test_net
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    container_name: web
    env_file: .env
    environment:
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      - some_test_net


networks:
  some_test_net:
volumes:
  pgdata: